--실습

CREATE TABLE MEMBER(
	NAME VARCHAR (50) NOT NULL,
	MID VARCHAR(50) NOT NULL ,
	PASSWORD VARCHAR(100) NOT NULL,
	ROLE VARCHAR(10) NOT NULL DEFAULT 'USER'
);

INSERT INTO MEMBER(MID, PASSWORD, NAME) VALUES ('YN', 1234, '예나');
INSERT INTO MEMBER(MID, PASSWORD, NAME, ROLE) VALUES ('ADMIN', 1234, '관리자', 'ADMIN');
SELECT MID, PASSWORD, ROLE FROM MEMBER WHERE MID='YN' AND PASSWORD='1234';

SELECT MID, PASSWORD FROM MEMBER WHERE MID='YN' AND PASSWORD='1234';


--나혼자
CREATE TABLE MEMBER (
    MEMBER_NAME VARCHAR(50),  -- 회원 이름
    MEMBER_ID VARCHAR(50) NOT NULL UNIQUE,      -- 회원 아이디 (고유, NULL 불가)
    MEMBER_PASSWORD VARCHAR(100) NOT NULL       -- 회원 비밀번호 (NULL 불가)
);



-- 새로운 회원 추가
INSERT INTO MEMBER (MEMBER_NAME, MEMBER_ID, MEMBER_PASSWORD) VALUES ('예나', 'YN', '1234');
SELECT MEMBER_NAME FROM MEMBER WHERE MEMBER_ID='YN' AND MEMBER_PASSWORD='1234';


-- 모든 회원 조회
SELECT * FROM MEMBER;



DROP TABLE MEMBER;