CREATE TABLE MEMBER (
    MEMBER_NUM INT PRIMARY KEY AUTO_INCREMENT,  -- 회원 번호 (기본 키, 자동 증가)
    MEMBER_ID VARCHAR(50) NOT NULL UNIQUE,      -- 회원 아이디 (고유, NULL 불가)
    MEMBER_PASSWORD VARCHAR(100) NOT NULL       -- 회원 비밀번호 (NULL 불가)
);

-- 새로운 회원 추가
INSERT INTO MEMBER (MEMBER_ID, MEMBER_PASSWORD) VALUES ('YN', '1234');
SELECT MEMBER_NUM, MEMBER_ID, MEMBER_PASSWORD FROM MEMBER; -- 모든 회원 조회
SELECT MEMBER_NUM, MEMBER_ID, MEMBER_PASSWORD FROM MEMBER WHERE MEMBER_ID = ? AND MEMBER_PASSWORD = ?; -- 특정 회원 조회
UPDATE MEMBER SET MEMBER_PASSWORD = ? WHERE MEMBER_ID = ?; -- 비밀번호 수정
DELETE FROM MEMBER WHERE MEMBER_ID = ?; -- 회원 삭제

-- 모든 회원 조회
SELECT * FROM MEMBER;

-- 특정 회원 조회
SELECT * FROM MEMBER WHERE MEMBER_ID = 'user1';

-- 특정 회원 삭제
DELETE FROM MEMBER WHERE MEMBER_ID = 'user1';

-- 샘플 데이터 삽입
INSERT INTO MEMBER (MEMBER_ID, MEMBER_PASSWORD) VALUES ('user1', 'password1');
INSERT INTO MEMBER (MEMBER_ID, MEMBER_PASSWORD) VALUES ('user2', 'password2');
INSERT INTO MEMBER (MEMBER_ID, MEMBER_PASSWORD) VALUES ('user3', 'password3');

DROP TABLE MEMBER;